# Runs on every node in the cluster
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: setup-172-route
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: route-setup
  template:
    metadata:
      labels:
        name: route-setup
    spec:
      hostNetwork: true
      tolerations:
      - operator: Exists
        effect: NoSchedule
      - operator: Exists
        effect: NoExecute
      restartPolicy: Always
      containers:
      - name: route-setup
        image: alpine:latest
        command:
        - sh
        - -c
        - |
          apk add --no-cache iproute2
          
          echo "Current routing table on $(hostname):"
          ip route show
          
          echo "Adding route: 172.16.0.0/16 via 10.0.0.1"
          ip route add 172.16.0.0/16 via 10.0.0.1 2>/dev/null || echo "Route may already exist"
          
          echo "Updated routing table on $(hostname):"
          ip route show | grep -E "(172\.16|10\.0)"
          
          echo "Testing connectivity to 10.0.0.1:"
          ping -c 2 10.0.0.1 || echo "Gateway not reachable"
          
          # Keep container running to maintain the route
          echo "Route setup complete on $(hostname). Keeping container alive..."
          while true; do
            sleep 300
            # Verify route still exists every 5 minutes
            ip route show | grep -q "172.16.0.0/16 via 10.0.0.1" || {
              echo "Route missing, re-adding..."
              ip route add 172.16.0.0/16 via 10.0.0.1 2>/dev/null || true
            }
          done
        securityContext:
          privileged: true